title: 2D MAZE GAME
email: 'mbula.angelah@gmail.com'
description: ...
baseurl: ...
url: https://AngelahMbula.github.io
twitter_username: ...
github_username: AngelahMbula
author: mbula.angelah@gmail.com

markdown: kramdown
theme: cayman
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-polyglot
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

# pagination
permalink: /:year/:month/
pagination:
  enabled: true
  per_page: 12
  sort_reverse: true
  limit: 0
  sort_field: 'date'
  permalink: '/page/:num/'
  title: ':title'
  trail:
    before: 2
    after: 2

# multilang
languages: ['ja', 'ko', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false
